# -*- coding: utf-8 -*-
"""Series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jowk6hLnaTKYcHaq8KeXel0kyGRFTyds
"""

import pandas as pd
from pandas import Series, DataFrame

sales = Series([120,150,180,210])

print(sales )

mark = pd.Series([71,81,69,90])
mark.values

mark.index

temp = pd.Series([28,31,30,29] ,index = ['mon','tue','wed','thu'])
print(temp)

population = pd.Series([35, 42, 31], index=['delhi','mumbai','jaipur'])
population['jaipur']

score = pd.Series([35, 68, 44, 79, 52])
score[score>50]

subjects = Series([76, 83, 91], index=['physics','chemistry','maths'])
'chemistry' in subjects.index

d= subjects.to_dict
print(d)

prices ={'pen':10 , 'notebook':50,'bag': 700}

prices_series = pd.Series(prices)
prices

"""it will use key as an index

"""

data = {'A': 10, 'B': 20, 'C': 30}
s = Series(data, index=['A', 'B', 'C', 'D'])
print(s.isna())

s.notnull()

sales.name = 'sales'
sales.index.name = 'monthly sales'
print(sales)

s=pd.Series([18,45,27,61],index=['p','q','r','s'])
s[s>30]

s = Series([500, 600, 700], index=['east','west','north'])
'west' in s

500 in s

#no label
city = {'delhi':80,'pune':65,'kochi':70}
pd.Series(city)

s = Series({"W": 5, "X": 10, "Y": 15}, index=["W", "X", "Y", "Z"])
pd.isnull(s)

pd.notnull(s)

s1 = pd.Series([10, 20, 30], index=["A", "B", "C"])
s2 = pd.Series([1, 2, 3], index=["C", "A", "B"])
result = s1 + s2
print(result)

s1 = pd.Series({"A": 12, "B": 18})
s2 = pd.Series({"B": 5, "C": 9})
result = s1 + s2
print(result)

stock = Series([25, 40, 18], index=["Item1", "Item2", "Item3"])
stock_dict = stock.to_dict()
pd.Series(stock_dict)

marks = {"Maths": 88, "Science": 74, "English": 69, "History": 81}
s= pd.Series(marks)
s[s>70]

rev = pd.Series([100,200], index=['north','south'])
rev.name="revenue"
rev.index.name="month"
rev

# jan and apr will null
north = Series({"Jan": 40, "Feb": 55, "Mar": 60})
south = Series({"Feb": 20, "Mar": 25, "Apr": 30})
total = north + south
print(total)

